FROM tensorflow/tensorflow:latest-devel-py3
MAINTAINER Anton Latukha <anton.latukha+docker@gmail.com>


## Set user-wide PATH Haskell Stack packages
ENV DEBIAN_FRONTEND=noninteractive \
    PATH=/root/.local/bin:"$PATH"


RUN apt update


## Install Stack with its dependencies
RUN curl -sSL https://get.haskellstack.org/ | sh


## IHaskell
### Install IHaskell system package dependencies
RUN apt install -y \
        python3-pip git \
        libtinfo-dev \
        libzmq3-dev \
        libcairo2-dev \
        libpango1.0-dev \
        libmagic-dev \
        libblas-dev \
        liblapack-dev


### Get IHaskell code, setup GHC, compile&install IHaskell Haskell dependencies, and then compile&install IHaskell itself
WORKDIR /root/IHaskell
RUN git clone --depth 1 https://github.com/gibiansky/IHaskell.git .
RUN pip3 install -r requirements.txt
RUN stack setup
RUN stack install --ghc-options=-O2 gtk2hs-buildtools
RUN stack install --ghc-options=-O2


## Tensorflow bindings
### Install system package dependencies (https://github.com/tensorflow/haskell)
RUN apt install -y \
    libsnappy-dev \
    libncurses5-dev \
    libgmp-dev \
    locales


### Install protobuf & libtensorlow-cpu
ENV PROTOBUF_V=3.3.0 \
    LIBTFLOWCPU_V=1.0.0
RUN apt install unzip
RUN curl -O -L \
    https://github.com/google/protobuf/releases/download/v"$PROTOBUF_V"/protoc-"$PROTOBUF_V"-linux-x86_64.zip && \
    unzip -d /usr/local protoc-"$PROTOBUF_V"-linux-x86_64.zip bin/protoc && \
    rm /usr/local protoc-"$PROTOBUF_V"-linux-x86_64.zip && \
    chmod 755 /usr/local/bin/protoc && \
    curl -L https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-"$LIBTFLOWCPU_V".tar.gz | tar -xz -C /usr/local && \
    ldconfig


### Install Tensorflow Haskell dependencies and bindings itself
RUN stack install --ghc-options=-O2 \
        snappy \
        snappy-framing \
        tensorflow-proto \
        tensorflow \
        tensorflow-core-ops \
        tensorflow-ops \
        tensorflow-records \
        tensorflow-records-conduit \
        tensorflow-test \
        tensorflow-opgen \
        tensorflow-logging


## Activate IHaskell Stack
RUN ihaskell install --stack


## Jupyter

### Generate default config
#RUN stack exec jupyter -- notebook --generate-config
#### Config written to /root/.jupyter/jupyter_notebook_config.py

### Configure
#### c.NotebookApp.password_required = True and
#### c.KernelManager.autorestart = True
#### give in Tensorflow Python 2.7:
#### Unexpected error Encountered error: 500 Server Error: Internal Server Error ("Unknown instruction: C.NOTEBOOKAPP.PASSWORD_REQUIRED")

## Run Jupyter server
EXPOSE 8888
WORKDIR "$HOME"/git
CMD stack exec jupyter -- notebook --allow-root
